// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryLendingSystem_Service.Models
{
    public partial class Book
    {
        public string Isbn { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Introduction { get; set; }
    }
}