// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryLendingSystem_Service.Models
{
    public partial class BorrowingRecord
    {
        public int UserId { get; set; }
        public int InventoryId { get; set; }
        public DateTime BorrowingTime { get; set; }
        public DateTime ReturnTime { get; set; }
    }
}