// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryLendingSystem_Service.Models
{
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public string Isbn { get; set; }
        public DateTime StoreTime { get; set; }
        public int StatusId { get; set; }
    }
}