// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LibraryLendingSystem_Service.Models
{
    public partial class LendStatus
    {
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    }
}